{{- if not .Values.existingSecret -}}
{{- $hasSecrets := or .Values.webhook.url .Values.gitops.token .Values.registry.credentials .Values.ecr.accessKeyId -}}
{{- if $hasSecrets -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "containrdog.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "containrdog.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.webhook.url }}
  WEBHOOK_URL: {{ .Values.webhook.url | quote }}
  {{- end }}
  {{- if .Values.gitops.token }}
  GITOPS_TOKEN: {{ .Values.gitops.token | quote }}
  {{- end }}
  {{- if .Values.registry.credentials }}
  REGISTRY_CREDENTIALS: {{ .Values.registry.credentials | quote }}
  {{- end }}
  {{- if .Values.ecr.accessKeyId }}
  AWS_ACCESS_KEY_ID: {{ .Values.ecr.accessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.ecr.secretAccessKey | quote }}
  {{- end }}
{{- end }}
{{- end }}
