{{- if .Values.ui.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "containrdog.fullname" . }}-ui
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "containrdog.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ui.service.type }}
  selector:
    {{- include "containrdog.selectorLabels" . | nindent 4 }}
  ports:
    - name: ui
      port: {{ .Values.ui.port }}
      targetPort: ui
      protocol: TCP
{{- end }}
